# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 前端博客
email: liangguanghui@ztgt.cn
description: >
  中投国泰前端博客，希望大家将自己在项目中遇见的问题、解决的方法、或者自己的生活po出来，相互讨论，共同进步。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ztgtfe.github.io/" # the base hostname & protocol for your site
github_username:  ztgtfe

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: redcarpet                         #markdown解释器
